version: '3'

services:
  spark:
    build: .
    environment:
      - FILE_WITH_HEADER_PATH=/spark/data/file_with_header/file_with_header.csv
      - FILE_WITHOUT_HEADER_PATH=/spark/data/file_without_header/file_without_header.csv
      - GEN_FILE_WITH_HEADER=/spark/data/file_with_header/gen_files_with_header.csv
      - GEN_FILE_WITHOUT_HEADER=/spark/data/file_without_header/gen_files_without_header.csv
    volumes:
      - ./file_with_header:/data/file_with_header
      - ./file_without_header:/data/file_without_header

  historyserver:
    image: gcr.io/spark-operator/spark:v3.4.0
    command: 
      - /sbin/tini
      - -s
      - --
      - /opt/spark/bin/spark-class
      - -Dspark.history.fs.logDirectory=/logs/
      - org.apache.spark.deploy.history.HistoryServer
    volumes:
      - ./logs:/logs
